TRANSLATIONS = {
    "EN": {
        "title": "WebHTC: XR Accessibility Suite",
        "console_name": "WebHTC MAIN CONSOLE",
        "visual_feed": "LIVE TRACKING FEED",
        "identity": "LICENSE & IDENTITY",
        "user_label": "TRACKING NODE: ",
        "env_label": "ENVIRONMENT: ",
        "calib_title": "SPATIAL CALIBRATION",
        "sensitivity": "DETECTION SCALE",
        "vert_off": "VERTICAL OFFSET",
        "depth_off": "DEPTH OFFSET",
        "reset_btn": "RESET COORDINATES",
        "engine_mode": "TRACKING ARCHITECTURE",
        "performance": "ENGINE OPTIMIZATION",
        "complexity": "NEURAL COMPLEXITY",
        "conf_det": "DETECTION THRESHOLD",
        "conf_tra": "TRACKING THRESHOLD",
        "smoothing": "TEMPORAL SMOOTHING",
        "system": "SYSTEM INTERFACE",
        "save_reboot": "APPLY CHANGES & RESTART",
        "status_offline": "OFFLINE",
        "status_scanning": "SCANNING...",
        "status_tracking": "TRACKING ACTIVE",
        "status_searching": "SEARCHING FOR TARGET",
        "cam_source": "CAMERA SOURCE",
        "use_fingers": "ENABLE FINGER TRACKING (EXPERIMENTAL)",
        "footer": "WEBHTC OPEN SOURCE PROJECT | ACCESSIBILITY FOR ALL",
        "theme_label": "INTERFACE STYLE",
        "lang_label": "LANGUAGE",
        "wizard_title": "WEBHTC SETUP WIZARD",
        "wizard_welcome": "WELCOME OPERATOR",
        "wizard_driver": "VMT DRIVER SETUP",
        "wizard_diag": "SYSTEM DIAGNOSTICS",
        "wizard_ready": "SYSTEM READY",
        "diag_steamvr": "STEAMVR STATUS",
        "diag_vmt": "VMT DRIVER LINK",
        "diag_camera": "OPTICAL SENSORS",
        "boot_init": "INITIALIZING SYSTEM...",
        "boot_check": "CHECKING SUBSYSTEM: ",
        "boot_done": "SYSTEM STABLE. READY.",
        "rerun_wizard": "RE-RUN SETUP WIZARD"
    },
    "RU": {
        "title": "WebHTC: Доступный XR",
        "console_name": "ОСНОВНАЯ КОНСОЛЬ WebHTC",
        "visual_feed": "ПРЯМОЙ ЭФИР ТРЕКИНГА",
        "identity": "ЛИЦЕНЗИЯ И ЛИЧНОСТЬ",
        "user_label": "УЗЕЛ ТРЕКИНГА: ",
        "env_label": "ОКРУЖЕНИЕ: ",
        "calib_title": "ПРОСТРАНСТВЕННАЯ КАЛИБРОВКА",
        "sensitivity": "МАСШТАБ ДЕТЕКЦИИ",
        "vert_off": "ВЕРТИКАЛЬНЫЙ СДВИГ",
        "depth_off": "ГЛУБИННЫЙ СДВИГ",
        "reset_btn": "СБРОС КООРДИНАТ",
        "engine_mode": "АРХИТЕКТУРА ТРЕКИНГА",
        "performance": "ОПТИМИЗАЦИЯ ДВИЖКА",
        "complexity": "НЕЙРОННАЯ СЛОЖНОСТЬ",
        "conf_det": "ПОРОГ ОБНАРУЖЕНИЯ",
        "conf_tra": "ПОРОГ ОТСЛЕЖИВАНИЯ",
        "smoothing": "ВРЕМЕННОЕ СГЛАЖИВАНИЕ",
        "system": "СИСТЕМНЫЙ ИНТЕРФЕЙС",
        "save_reboot": "ПРИМЕНИТЬ И ПЕРЕЗАГРУЗИТЬ",
        "status_offline": "ОФФЛАЙН",
        "status_scanning": "СКАНИРОВАНИЕ...",
        "status_tracking": "ТРЕКИНГ АКТИВЕН",
        "status_searching": "ПОИСК ЦЕЛИ",
        "cam_source": "ИСТОЧНИК КАМЕРЫ",
        "use_fingers": "ВКЛЮЧИТЬ ТРЕКИНГ ПАЛЬЦЕВ (ЭКСПЕРИМЕНТАЛЬНО)",
        "footer": "ПРОЕКТ WebHTC | ДОСТУПНЫЙ VR ДЛЯ ВСЕХ",
        "theme_label": "СТИЛЬ ИНТЕРФЕЙСА",
        "lang_label": "ЯЗЫК",
        "wizard_title": "МАСТЕР УСТАНОВКИ WEBHTC",
        "wizard_welcome": "ДОБРО ПОЖАЛОВАТЬ, ОПЕРАТОР",
        "wizard_driver": "УСТАНОВКА ДРАЙВЕРА VMT",
        "wizard_diag": "СИСТЕМНАЯ ДИАГНОСТИКА",
        "wizard_ready": "СИСТЕМА ГОТОВА",
        "diag_steamvr": "СТАТУС STEAMVR",
        "diag_vmt": "СВЯЗЬ С ДРАЙВЕРОМ VMT",
        "diag_camera": "ОПТИЧЕСКИЕ ДАТЧИКИ",
        "boot_init": "ИНИЦИАЛИЗАЦИЯ СИСТЕМЫ...",
        "boot_check": "ПРОВЕРКА ПОДСИСТЕМЫ: ",
        "boot_done": "СИСТЕМА СТАБИЛЬНА. ГОТОВО.",
        "rerun_wizard": "ПЕРЕЗАПУСТИТЬ МАСТЕР НАСТРОЙКИ"
    }
}
